model = "gpt-5-codex"
model_reasoning_effort = "high"
[projects."/home/nazif/proje/yildiz-bayan-kuaforu"]
trust_level = "trusted"

[mcp_servers]
[mcp_servers.context7]
command = "npx"
args = [ "-y", "@smithery/cli@latest", "run", "@upstash/context7-mcp", "--key", "922bd5eb-99fb-4328-a056-2ca64a208261" ]


